suryanshsingh2001/MyLibrary

- README.md
- client/Dockerfile
- client/vite.config.js
- Dockerfiles for frontend and backend components are added.
- Docker Compose configuration is included.
- Environment variables and dependencies are defined.
- Documentation is updated with Docker setup instructions.
- The Dockerized project has been tested locally to ensure it functions as expected.
- Updated project documentation to include Docker setup instructions.
---
> Dockerizing the Project

- client/src/Components/Cart.jsx
fixes #8
https://github.com/suryanshsingh2001/MyLibrary/assets/110036553/bc3fefc0-a916-4a0a-abcc-9a9dc84967bd
> Shopping card UI has been improved

- client/src/App.jsx
- client/src/Components/BookList.jsx
- client/src/Components/Footer.jsx
- client/src/Components/Header.jsx
- client/src/Components/Search.jsx
- client/tailwind.config.js
Hi there, I fixed the lack of responsiveness 
**Consideration**
It is not recommended to display the user's name in the header for optimal UI and UX. A better approach would be to use an image or avatar of the user with their first name displayed below it. This can serve as a link to the user's profile or any related page. However, for now, the "Hello to  userName" span is responsive and functional on all devices, as shown in the accompanying screenshots.
**Mobile**
**Tablet**
**Desktop**
I hope you like these improvements. Feel free to ask any questions. Once you're satisfied, merge this pull request and I'll work on another issue. Thank you!
> #6 App is fully responsive now

- client/src/Components/BookList.jsx
- client/src/Components/Cart.jsx
Issue: Weird Size of Call to Action Buttons on Smaller Devices #14
> Clear Cart fixed

- client/src/Components/BookList.jsx
- client/src/Components/Cart.jsx
> class changed to className

- client/src/Components/Cart.jsx
This pull request enhances the user experience by centering the H1 tag for the shopping cart using Tailwind CSS.
- Centered the H1 tag for the shopping cart.
> Enhance UX: Improve Shopping Cart Title

- client/src/index.css
>  Feat : Added custom scroll bar

- client/src/Components/Search.jsx
>  Fixes : Arrow keys on select removed

- blogs /technicalBlog.md
I have created a technical Blog for MyLibrary.
fixes #2
> Created A technicalBlog for MyLibrary 

- client/src/Components/Search.jsx
Made the color palette acc to the theme of the site
>  Feat : Added more styling to search bar

- .github/ISSUE_TEMPLATE/dependabot.yml
> Dependabot added

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/Components/TopButton.jsx
- client/src/Components/index.js
**Title:** Add back to top button
**Description:**
This PR addresses issue #38, which requested the addition of a "Back to Top" button.
**Changes Made:**
- Added back to top button and made some necessary changes.
- The button works on both desktop and mobile.
- An extra dependency was installed.
**Screenshot:**
> Add back to top button

- client/src/Components/TopButton.jsx
**Title:** Add hover effect to back to top button
**Description:**
This PR addresses issue #40, which requested the addition of hover effect to "Back to Top" button.
**Changes Made:**
- Added hover effect to back to top button.
> Add hover effect to back to top button

- client/src/Components/Footer.jsx
issue no: #21 
Changed the look of Github link button in footer.
> Changed the look of Github navigation button

- design/Improved Layout Design for Book Lists
#Improved Layout Design for Book Lists
This pull request showcases a comprehensive UI/UX redesign for the book lists layout in the MyLibrary 📚 web application. The MyLibrary app is a modern library management tool developed using React.js, featuring 🔐 Auth0 for authentication and utilizing 📖 Google Books API for book data. The user interface has been styled with 🎨 Tailwind CSS to provide an exceptional user experience.
The primary goal of this redesign is to elevate both the user interface (UI) and user experience (UX) of the book lists within the MyLibrary project. We have focused on proposing an improved layout design that enhances accessibility, usability, and visual appeal.
> Create Improved Layout Design for Book Lists

- client/src/Components/Cart.jsx
- client/src/Components/Footer.jsx
**Fix #50:** Wrong Usage of Class HTML Attribute
This pull request addresses the incorrect usage of the class HTML attribute within the application. The changes include fixing the attribute to ensure proper styling and functionality.
---
**Commits Overview**
53115b87: Fix on wrong usage of class HTML attribute
Corrected the usage of the class attribute in HTML elements to ensure proper application of styles and adherence to HTML standards.
This commit resolves issue #50.
---
**Summary**
These changes correct the improper usage of the class HTML attribute, ensuring that styles are correctly applied and the application adheres to HTML standards. This fix improves the overall maintainability and functionality of the codebase.
fix #50
> Fix on wrong usage of class HTML attribute

- client/src/Components/Search.jsx
Property changed in Search.jsx component.
> Search Loading Icon #48

- client/src/Components/BookList.jsx
The **Add to Cart** button was inconsistent which resulted in a bad user experience.
Fixed the button in the bottom right corner.
Acceptence- [#58](https://github.com/suryanshsingh2001/MyLibrary/issues/58)
> fixed add-to-cart button

- client/src/Components/BookList.jsx
Added intersection observer for detecting user scroll and created infinite scrolling based on that with Google Books api queries.
This PR addresses issue #56
> add infinite scroll

- client/src/Components/BookList.jsx
Reverts suryanshsingh2001/MyLibrary#60
> Revert "add infinite scroll"
